version: "3"
services:
    node_backend:
        command: npm run serve
        environment:
            - NODE_ENV=development
        volumes:
          - ./:/app
          - node_modules:/app/node_modules


volumes:
    node_modules:
        driver: local
        driver_opts:
            type: none
            device: ./node_modules
            o: bind